travis:
  secure:
    BINSTAR_TOKEN: ntSQvW7Kq2hio6Qz0Fk+0ptE/IiSVw31X4fwQPQMPvKBvw0ItIiwot7ERyp4+qrtq3P6Aj6X0CKnKzgnCiTZvNh5hCfMuljQRyFGsry+QSbjk6HzG7KzttBeB+aGXKtVQ8HexWWxXdRoYubnK84FjVP6XQza0+P+SlA4e7iCnh2CL1VHJjoNxj8dKo0TN5tVpVd6umunb2r5GLALyyn1BYw+QbZeN4+TyecgswS9GuW4Oxqovv64B3O4WTnrTtPhmdeRxLINxtNNOVIEV7BjJs3GmBWM2CRsqab/PJ14nUL5YPfc85hHKY1XvaEHB8cq/loKo/4o9dkS0BRFxSjH2cXnQXL7xS7/ILU19DThnySo8J9Q09z/XK5VAdf3wUbG0zFRtuYt1RXF6R8JvLMBU3yW2itqmn66Qks35MW8T5PY4lCRru3X/Kx3xI+SNp8XDbubNXgrMO2dpdx53VVp4N0GWQwO0JrEVSBcHuWLIipmWuDhnYgKUoV8RvP6etENp2C9gVCuesmtIJEofBOmcYJ4ErzzhRKlhsvZwnbdzca/upDBQtRJJeiESzFrXrvvUKu4pbj7aJx0smkP2fF2y5J0OQRQtkNaoNlv4JMZK2yCdsGYlxG3oqPFhHkAyRV5Nkvq81/1KwOIzRy8gltJcXDsUA+hADaArDRMlWiAVyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
